language: python

cache: pip

os:
  - linux
  - osx

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - pip install pipenv
  - pipenv install --dev --skip-lock

script:
  - pipenv run pytest --cov=amortization --cov-report=xml -v
  - pipenv run pycodestyle --verbose

after_success:
  - pipenv run codecov

deploy:
  provider: pypi
  user: $TEST_PYPI_USER
  password: $TEST_PYPI_PASS
  server: https://test.pypi.org/legacy/
  distributions: "sdist"
  on:
    branch: develop
    condition: $TRAVIS_PYTHON_VERSION = "3.6"